filter:
    paths:
        - src/*
    excluded_paths:
        - tests/*
tools:
    php_code_sniffer: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer:
        config: { level: psr2 }
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
        runs: 2
checks:
    php:
        code_rating: true
        duplication: true
